### ISSUE TITLE
No annotation files in dataset

### ISSUE THREAD

**Issue by yueyusisi** [bridgeqiqi/S2FPR#3]
Why did I download the data set with only pictures and no labeled files? Will the annotation files be added later?

**Comment by KingMV** [comment]
In fact, Self-supervised learning does not require manual annotation, @yueyusisi

**Comment by yueyusisi** [comment]
So how do I calculate the accuracy of my predictions?

>

**Comment by bridgeqiqi** [comment]
@yueyusisi You can refer to the test.py or just simply run the test.py file to calculate the two common metrics MAE and RMSE.
